# Generated by Django 4.1.7 on 2023-04-04 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_adopted_alter_pet_tutor_alter_profile_is_tutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='date_finished',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
