# Generated by Django 4.1.7 on 2023-04-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_adoption_date_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='shelter',
        ),
    ]
