# Generated by Django 4.1.7 on 2023-03-30 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrazilStates',
            fields=[
                ('short_name', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('city', models.CharField(max_length=100)),
                ('about', models.CharField(blank=True, max_length=480)),
                ('is_tutor', models.BooleanField(default=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estado', to='user.brazilstates')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
